backend:
  name: github
  repo: sekizuihan/mypage
  branch: main
  base_url: https://sekizuihan.com/oauth

media_folder: "img/uploads"
public_folder: "/img/uploads"

locale: ja

collections:
  - name: "works"
    label: "作品一覧"
    files:
      - name: "works_index"
        label: "作品カード一覧"
        file: "content/works-index.json"
        fields:
          - label: "作品"
            name: "works"
            widget: "list"
            collapsed: false
            summary: "{{fields.name}}"
            fields:
              - label: "リンク先URL"
                name: "url"
                widget: "string"
              - label: "サムネイル画像"
                name: "image"
                widget: "image"
              - label: "画像のalt属性"
                name: "alt"
                widget: "string"
              - label: "作品名・種別"
                name: "name"
                widget: "string"
              - label: "使用ツール・年"
                name: "tools"
                widget: "string"

  - name: "other_works"
    label: "Other works"
    files:
      - name: "other_works_list"
        label: "その他の活動一覧"
        file: "content/other-works.json"
        fields:
          - label: "活動リスト"
            name: "items"
            widget: "list"
            collapsed: false
            summary: "{{fields.date}}　{{fields.title}}"
            fields:
              - label: "日付"
                name: "date"
                widget: "string"
              - label: "活動内容"
                name: "title"
                widget: "string"
              - label: "リンクURL"
                name: "link"
                widget: "string"
                required: false
              - label: "リンクのラベル"
                name: "linkLabel"
                widget: "string"
                required: false